language: minimal

matrix:
    include:
        - name: "Build direwolf-git"
          env: TARGET=build PACKAGE=direwolf-git

        - name: "Build kalibrate-bladerf-git"
          env: TARGET=build PACKAGE=kalibrate-bladerf-git

        - name: "Build nerd-fonts-roboto-mono"
          env: TARGET=build PACKAGE=nerd-fonts-roboto-mono

        - name: "Build steam-fonts"
          env: TARGET=build PACKAGE=steam-fonts

        - name: "Build vna_j"
          env: TARGET=build PACKAGE=vna_j

        - name: "Build dwarview-git"
          env: TARGET=build PACKAGE=dwarview-git

        - name: "Build nerd-fonts-droid-sans-mono"
          env: TARGET=build PACKAGE=nerd-fonts-droid-sans-mono

        - name: "Build python-pyxel"
          env: TARGET=build PACKAGE=python-pyxel
        - name: "Check version of python-pyxel"
          env: TARGET=version PACKAGE=python-pyxel

        - name: "Build usbsoftrock"
          env: TARGET=build PACKAGE=usbsoftrock

before_install:
    - .travis/prepare.sh $TARGET

script:
    - .travis/run-test.sh $TARGET $PACKAGE
